dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable --allow-unauthenticated

# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  # - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run test:coveralls

notifications:
  email: false
